services:
  db:
    image: postgres:17
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  app:
    build: .
    stdin_open: true
    env_file:
      - .env
    tty: true
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "${PUBLIC_PORT}:3000"
    depends_on:
      - db

volumes:
  bundle_cache:
